/**
 * @file tpl_app_config.c
 *
 * @section desc File description
 *
 * OS data structure generated from application blink
 * Automatically generated by goil on Tue Apr 15 17:27:29 2025
 * from root OIL file main.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include <stdbool.h>
#include <stdint.h>

#include "tpl_app_config.h"

#include "tpl_os_internal_types.h"
#include "tpl_machine.h"
#include "tpl_os_interrupt.h"
#include "tpl_os_interrupt_kernel.h"
#include "tpl_os_alarm_kernel.h"
#include "tpl_os_alarm.h"
#include "tpl_os_resource_kernel.h"
#include "tpl_os_resource.h"
#include "tpl_os_event_kernel.h"
#include "tpl_os_event.h"
#include "tpl_os_action.h"
#include "tpl_os_kernel.h"
#include "tpl_os_definitions.h"


/*=============================================================================
 * Application Modes tables for tasks, alarms and schedule tables
 * Application Modes masks are as follow:
 * Std = 1
 */

CONST(tpl_application_mode, OS_CONST) Std = 0; /* mask = 1 */
CONST(tpl_application_mode, OS_CONST) OSDEFAULTAPPMODE = 0;
CONST(tpl_appmode_mask, OS_CONST) tpl_task_app_mode[TASK_COUNT] = {
  0 /* task write_audio :  */ ,
  0 /* task inference :  */ ,
  1 /* task copyDMAtoSRAM : Std */ ,
  0 /* task start_dma :  */ ,
  1 /* task start_audio : Std */ ,
  1 /* task setup_inference : Std */ ,
  1 /* task start_sdcard : Std */ 
};

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of event masks
 */

/* Event ev_NORMALIZE */
#define ev_NORMALIZE_mask 1
CONST(EventMaskType, AUTOMATIC) ev_NORMALIZE = ev_NORMALIZE_mask;

/* Event ev_write_audio */
#define ev_write_audio_mask 1
CONST(EventMaskType, AUTOMATIC) ev_write_audio = ev_write_audio_mask;

/* Event ev_DMAtoSRAM */
#define ev_DMAtoSRAM_mask 1
CONST(EventMaskType, AUTOMATIC) ev_DMAtoSRAM = ev_DMAtoSRAM_mask;

/*=============================================================================
 * Declaration of processes IDs
 */

/* Task write_audio identifier */
#define write_audio_id 0
CONST(TaskType, AUTOMATIC) write_audio = write_audio_id;

/* Task inference identifier */
#define inference_id 1
CONST(TaskType, AUTOMATIC) inference = inference_id;

/* Task copyDMAtoSRAM identifier */
#define copyDMAtoSRAM_id 2
CONST(TaskType, AUTOMATIC) copyDMAtoSRAM = copyDMAtoSRAM_id;

/* Task start_dma identifier */
#define start_dma_id 3
CONST(TaskType, AUTOMATIC) start_dma = start_dma_id;

/* Task start_audio identifier */
#define start_audio_id 4
CONST(TaskType, AUTOMATIC) start_audio = start_audio_id;

/* Task setup_inference identifier */
#define setup_inference_id 5
CONST(TaskType, AUTOMATIC) setup_inference = setup_inference_id;

/* Task start_sdcard identifier */
#define start_sdcard_id 6
CONST(TaskType, AUTOMATIC) start_sdcard = start_sdcard_id;

/* ISR isr_dma identifier */
#define isr_dma_id 7
#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/**
 * The scheduler resource descriptor.
 * One scheduler resource is defined per core.
 *
 * @see #RES_SCHEDULER
 */

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
VAR(tpl_resource, OS_VAR) res_sched_rez_desc = {
  RES_SCHEDULER_PRIORITY,   /*  ceiling priority                            */
  0,                        /*  owner_prev_priority                         */
  INVALID_PROC_ID,          /*  owner                                       */
#if WITH_OSAPPLICATION == YES
  INVALID_OSAPPLICATION_ID, /*  OS Application id                           */
#endif

  NULL                      /*  next_res                                    */
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_resource, AUTOMATIC, OS_APPL_DATA)
tpl_resource_table[RESOURCE_COUNT] = {
  &res_sched_rez_desc
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Definition and initialization of Counters related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Counter SystemCounter descriptor
 */

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_tick, OS_CONST) OSTICKSPERBASE = 1;
CONST(tpl_tick, OS_CONST) OSMAXALLOWEDVALUE = 65535;
CONST(tpl_tick, OS_CONST) OSMINCYCLE = 1;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_counter, OS_VAR) SystemCounter_counter_desc = {
  /* ticks per base       */  1,
  /* max allowed value    */  65535,
  /* minimum cycle        */  1,
  /* current tick         */  0,
  /* current date         */  0,
#if WITH_OSAPPLICATION == YES
    /* OS Application id    */  
#endif
    /* first alarm          */  NULL_PTR,
    /* next alarm to raise  */  NULL_PTR
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#include "tpl_os_kernel.h"          /* tpl_schedule */
#include "tpl_os_timeobj_kernel.h"  /* tpl_counter_tick */
#include "tpl_machine_interface.h"  /* tpl_switch_context_from_it */

#define OS_START_SEC_VAR_32BIT
#include "tpl_memmap.h"
volatile VAR(uint32, OS_VAR) tpl_time_counter = 0;
#define OS_STOP_SEC_VAR_32BIT
#include "tpl_memmap.h"

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(tpl_bool, OS_CODE) tpl_tick_SysTick(void)
{
  tpl_counter_tick(&SystemCounter_counter_desc);
  tpl_time_counter++;

  if (tpl_kern.need_schedule == TRUE)
  {
    tpl_schedule_from_running();
    LOCAL_SWITCH_CONTEXT()
  }

  return TRUE;
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Descriptor(s) of the idle task(s)
 */
/*-----------------------------------------------------------------------------
 * Task IDLE_TASK descriptor
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * Task IDLE_TASK function prototype
 */

FUNC(void, OS_APPL_CODE) idle_function(void);
#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task IDLE_TASK stack
 */
#define APP_Task_IDLE_TASK_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) IDLE_TASK_stack_zone[IDLE_STACK_SIZE/sizeof(tpl_stack_word)];
#define APP_Task_IDLE_TASK_STOP_SEC_STACK
#include "tpl_memmap.h"

#define IDLE_TASK_STACK {IDLE_TASK_stack_zone, IDLE_STACK_SIZE}

/*
 * Task IDLE_TASK context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) IDLE_TASK_int_context;

#define IDLE_TASK_CONTEXT &IDLE_TASK_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task IDLE_TASK
 */
CONST(tpl_proc_static, OS_CONST) IDLE_TASK_task_stat_desc = {
  /* context                  */  IDLE_TASK_CONTEXT,
  /* stack                    */  IDLE_TASK_STACK,
  /* entry point (function)   */  idle_function,
  /* internal ressource       */  NULL,
  /* task id                  */  IDLE_TASK_ID,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  0,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task IDLE_TASK
 */
VAR(tpl_proc, OS_VAR) IDLE_TASK_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  0,
  /* task state                     */  SUSPENDED
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Task related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Task write_audio descriptor
 */
#define APP_Task_write_audio_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task write_audio function prototype
 */

FUNC(void, OS_APPL_CODE) write_audio_function(void);
#define APP_Task_write_audio_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task write_audio stack
 */
#define APP_Task_write_audio_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) write_audio_stack_zone[2048/sizeof(tpl_stack_word)];
#define APP_Task_write_audio_STOP_SEC_STACK
#include "tpl_memmap.h"

#define write_audio_STACK {write_audio_stack_zone, 2048}

/*
 * Task write_audio context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) write_audio_int_context;

#define write_audio_CONTEXT &write_audio_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task write_audio
 */
CONST(tpl_proc_static, OS_CONST) write_audio_task_stat_desc = {
  /* context                  */  write_audio_CONTEXT,
  /* stack                    */  write_audio_STACK,
  /* entry point (function)   */  write_audio_function,
  /* internal ressource       */  NULL,
  /* task id                  */  write_audio_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  2,
  /* max activation count     */  1,
  /* task type                */  TASK_EXTENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task write_audio
 */
VAR(tpl_proc, OS_VAR) write_audio_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  2,
  /* task state                     */  SUSPENDED
};

/*
 * Event structure of task write_audio
 */
VAR(tpl_task_events, OS_VAR) write_audio_task_evts = {
  /* event set  */ 0,
  /* event wait */ 0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task inference descriptor
 */
#define APP_Task_inference_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task inference function prototype
 */

FUNC(void, OS_APPL_CODE) inference_function(void);
#define APP_Task_inference_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task inference stack
 */
#define APP_Task_inference_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) inference_stack_zone[2048/sizeof(tpl_stack_word)];
#define APP_Task_inference_STOP_SEC_STACK
#include "tpl_memmap.h"

#define inference_STACK {inference_stack_zone, 2048}

/*
 * Task inference context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) inference_int_context;

#define inference_CONTEXT &inference_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task inference
 */
CONST(tpl_proc_static, OS_CONST) inference_task_stat_desc = {
  /* context                  */  inference_CONTEXT,
  /* stack                    */  inference_STACK,
  /* entry point (function)   */  inference_function,
  /* internal ressource       */  NULL,
  /* task id                  */  inference_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  3,
  /* max activation count     */  1,
  /* task type                */  TASK_EXTENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task inference
 */
VAR(tpl_proc, OS_VAR) inference_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  3,
  /* task state                     */  SUSPENDED
};

/*
 * Event structure of task inference
 */
VAR(tpl_task_events, OS_VAR) inference_task_evts = {
  /* event set  */ 0,
  /* event wait */ 0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task copyDMAtoSRAM descriptor
 */
#define APP_Task_copyDMAtoSRAM_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task copyDMAtoSRAM function prototype
 */

FUNC(void, OS_APPL_CODE) copyDMAtoSRAM_function(void);
#define APP_Task_copyDMAtoSRAM_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task copyDMAtoSRAM stack
 */
#define APP_Task_copyDMAtoSRAM_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) copyDMAtoSRAM_stack_zone[1280/sizeof(tpl_stack_word)];
#define APP_Task_copyDMAtoSRAM_STOP_SEC_STACK
#include "tpl_memmap.h"

#define copyDMAtoSRAM_STACK {copyDMAtoSRAM_stack_zone, 1280}

/*
 * Task copyDMAtoSRAM context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) copyDMAtoSRAM_int_context;

#define copyDMAtoSRAM_CONTEXT &copyDMAtoSRAM_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task copyDMAtoSRAM
 */
CONST(tpl_proc_static, OS_CONST) copyDMAtoSRAM_task_stat_desc = {
  /* context                  */  copyDMAtoSRAM_CONTEXT,
  /* stack                    */  copyDMAtoSRAM_STACK,
  /* entry point (function)   */  copyDMAtoSRAM_function,
  /* internal ressource       */  NULL,
  /* task id                  */  copyDMAtoSRAM_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  4,
  /* max activation count     */  1,
  /* task type                */  TASK_EXTENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task copyDMAtoSRAM
 */
VAR(tpl_proc, OS_VAR) copyDMAtoSRAM_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  4,
  /* task state                     */  AUTOSTART
};

/*
 * Event structure of task copyDMAtoSRAM
 */
VAR(tpl_task_events, OS_VAR) copyDMAtoSRAM_task_evts = {
  /* event set  */ 0,
  /* event wait */ 0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task start_dma descriptor
 */
#define APP_Task_start_dma_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task start_dma function prototype
 */

FUNC(void, OS_APPL_CODE) start_dma_function(void);
#define APP_Task_start_dma_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task start_dma stack
 */
#define APP_Task_start_dma_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) start_dma_stack_zone[384/sizeof(tpl_stack_word)];
#define APP_Task_start_dma_STOP_SEC_STACK
#include "tpl_memmap.h"

#define start_dma_STACK {start_dma_stack_zone, 384}

/*
 * Task start_dma context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) start_dma_int_context;

#define start_dma_CONTEXT &start_dma_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task start_dma
 */
CONST(tpl_proc_static, OS_CONST) start_dma_task_stat_desc = {
  /* context                  */  start_dma_CONTEXT,
  /* stack                    */  start_dma_STACK,
  /* entry point (function)   */  start_dma_function,
  /* internal ressource       */  NULL,
  /* task id                  */  start_dma_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  1,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task start_dma
 */
VAR(tpl_proc, OS_VAR) start_dma_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  1,
  /* task state                     */  SUSPENDED
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task start_audio descriptor
 */
#define APP_Task_start_audio_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task start_audio function prototype
 */

FUNC(void, OS_APPL_CODE) start_audio_function(void);
#define APP_Task_start_audio_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task start_audio stack
 */
#define APP_Task_start_audio_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) start_audio_stack_zone[384/sizeof(tpl_stack_word)];
#define APP_Task_start_audio_STOP_SEC_STACK
#include "tpl_memmap.h"

#define start_audio_STACK {start_audio_stack_zone, 384}

/*
 * Task start_audio context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) start_audio_int_context;

#define start_audio_CONTEXT &start_audio_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task start_audio
 */
CONST(tpl_proc_static, OS_CONST) start_audio_task_stat_desc = {
  /* context                  */  start_audio_CONTEXT,
  /* stack                    */  start_audio_STACK,
  /* entry point (function)   */  start_audio_function,
  /* internal ressource       */  NULL,
  /* task id                  */  start_audio_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  1,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task start_audio
 */
VAR(tpl_proc, OS_VAR) start_audio_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  1,
  /* task state                     */  AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task setup_inference descriptor
 */
#define APP_Task_setup_inference_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task setup_inference function prototype
 */

FUNC(void, OS_APPL_CODE) setup_inference_function(void);
#define APP_Task_setup_inference_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task setup_inference stack
 */
#define APP_Task_setup_inference_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) setup_inference_stack_zone[11264/sizeof(tpl_stack_word)];
#define APP_Task_setup_inference_STOP_SEC_STACK
#include "tpl_memmap.h"

#define setup_inference_STACK {setup_inference_stack_zone, 11264}

/*
 * Task setup_inference context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) setup_inference_int_context;

#define setup_inference_CONTEXT &setup_inference_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task setup_inference
 */
CONST(tpl_proc_static, OS_CONST) setup_inference_task_stat_desc = {
  /* context                  */  setup_inference_CONTEXT,
  /* stack                    */  setup_inference_STACK,
  /* entry point (function)   */  setup_inference_function,
  /* internal ressource       */  NULL,
  /* task id                  */  setup_inference_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  4,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task setup_inference
 */
VAR(tpl_proc, OS_VAR) setup_inference_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  4,
  /* task state                     */  AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task start_sdcard descriptor
 */
#define APP_Task_start_sdcard_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task start_sdcard function prototype
 */

FUNC(void, OS_APPL_CODE) start_sdcard_function(void);
#define APP_Task_start_sdcard_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task start_sdcard stack
 */
#define APP_Task_start_sdcard_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) start_sdcard_stack_zone[512/sizeof(tpl_stack_word)];
#define APP_Task_start_sdcard_STOP_SEC_STACK
#include "tpl_memmap.h"

#define start_sdcard_STACK {start_sdcard_stack_zone, 512}

/*
 * Task start_sdcard context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) start_sdcard_int_context;

#define start_sdcard_CONTEXT &start_sdcard_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task start_sdcard
 */
CONST(tpl_proc_static, OS_CONST) start_sdcard_task_stat_desc = {
  /* context                  */  start_sdcard_CONTEXT,
  /* stack                    */  start_sdcard_STACK,
  /* entry point (function)   */  start_sdcard_function,
  /* internal ressource       */  NULL,
  /* task id                  */  start_sdcard_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  4,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task start_sdcard
 */
VAR(tpl_proc, OS_VAR) start_sdcard_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  4,
  /* task state                     */  AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of ISR2 related defines and structures
 */
/*-----------------------------------------------------------------------------
 * ISR isr_dma descriptor
 */
#define APP_ISR_isr_dma_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * ISR isr_dma function prototype
 */
FUNC(void, OS_APPL_CODE) isr_dma_function(void);
#define APP_ISR_isr_dma_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures of isr isr_dma
 */
/*
 * ISR isr_dma stack
 */
#define APP_ISR_isr_dma_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) isr_dma_stack_zone[384/sizeof(tpl_stack_word)];
#define APP_ISR_isr_dma_STOP_SEC_STACK
#include "tpl_memmap.h"

#define isr_dma_STACK {isr_dma_stack_zone, 384}

/*
 * ISR isr_dma context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) isr_dma_int_context;

#define isr_dma_CONTEXT &isr_dma_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"


/*
  No timing protection
 */

#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of ISR isr_dma
 */
CONST(tpl_proc_static, OS_CONST) isr_dma_isr_stat_desc = {
  /* context                  */  isr_dma_CONTEXT,
  /* stack                    */  isr_dma_STACK,
  /* entry point (function)   */  isr_dma_function,
  /* internal ressource       */  NULL,
  /* ISR id                   */  isr_dma_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif

  /* ISR base priority       */  6,
  /* ISR activation count     */  1,
  /* ISR type                */  IS_ROUTINE,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0,
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

CONST(tpl_isr_static, OS_CONST) isr_dma_isr_helper = {
  /* helper */ NULL,
  /* next */   NULL,
  /* id */     isr_dma_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of ISR isr_dma
 */
VAR(tpl_proc, OS_VAR) isr_dma_isr_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* ISR priority                   */  6,
  /* ISR state                      */  SUSPENDED
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_CODE
#include "tpl_memmap.h"
extern FUNC(void, OS_CODE) isr_rtc_function(void);

FUNC(void, OS_CODE) DMA_IRQ_Handler(void)
{
  /* ISR1s */

  /* ISR2s */
  GET_CURRENT_CORE_ID(core_id)

#if WITH_STACK_MONITORING == YES
  GET_TPL_KERN_FOR_CORE_ID(core_id, kern)
  tpl_check_stack((tpl_proc_id)TPL_KERN_REF(kern).running_id);
#endif /* WITH_AUTOSAR_STACK_MONITORING */

  tpl_fast_central_interrupt_handler(isr_dma_id);
  /* COUNTERs */
  /* ACK */

}

FUNC(void, OS_CODE) RTC_IRQ_Handler(void)
{
  /* ISR1s */
  isr_rtc_function();

  /* ISR2s */
  /* COUNTERs */
  /* ACK */

}

FUNC(void, OS_CODE) SysTick_Handler(void)
{
  /* ISR1s */

  /* ISR2s */
  /* COUNTERs */
  tpl_tick_SysTick();
  /* ACK */

}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*=============================================================================
 * Definition and initialization of process tables (tasks and isrs)
 */
CONSTP2CONST(tpl_proc_static, AUTOMATIC, OS_APPL_DATA)
tpl_stat_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &write_audio_task_stat_desc,
  &inference_task_stat_desc,
  &copyDMAtoSRAM_task_stat_desc,
  &start_dma_task_stat_desc,
  &start_audio_task_stat_desc,
  &setup_inference_task_stat_desc,
  &start_sdcard_task_stat_desc,
  &isr_dma_isr_stat_desc,
  &IDLE_TASK_task_stat_desc
};

CONSTP2VAR(tpl_proc, AUTOMATIC, OS_APPL_DATA)
tpl_dyn_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &write_audio_task_desc,
  &inference_task_desc,
  &copyDMAtoSRAM_task_desc,
  &start_dma_task_desc,
  &start_audio_task_desc,
  &setup_inference_task_desc,
  &start_sdcard_task_desc,
  &isr_dma_isr_desc,
  &IDLE_TASK_task_desc
};

CONSTP2VAR(tpl_task_events, AUTOMATIC, OS_APPL_DATA)
tpl_task_events_table[EXTENDED_TASK_COUNT] = {
  &write_audio_task_evts,
  &inference_task_evts,
  &copyDMAtoSRAM_task_evts
};

CONSTP2CONST(tpl_isr_static, AUTOMATIC, OS_APPL_DATA)
tpl_isr_stat_table[ISR_COUNT] = {
  &isr_dma_isr_helper
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Declaration of flags functions
 */
/* $FLAGSFUNCTIONS$ */

/*=============================================================================
 * Definition and initialization of Ready List structures
 */
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_heap_entry, OS_VAR) tpl_ready_list[11];
VAR(tpl_rank_count, OS_VAR) tpl_tail_for_prio[7] = {
  0,
  0,
  0,
  0,
  0,
  0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/**
 * @internal
 *
 * tpl_kern gather informations on the current executing object and
 * the previous one
 */
VAR(tpl_kern_state, OS_VAR) tpl_kern =
{
  NULL,                      /* no running task static descriptor   */
  &IDLE_TASK_task_stat_desc, /* elected task to run is idle task    */
  NULL,                      /* no running task dynamic descriptor  */
  &IDLE_TASK_task_desc,      /* elected task to run is idle task    */
  INVALID_PROC_ID,           /* no running task so no ID            */
  INVALID_PROC_ID,           /* idle task has no ID                 */
  NO_NEED_SWITCH,            /* no context switch needed at start   */
  FALSE,                     /* no schedule needed at start         */
#if WITH_MEMORY_PROTECTION == YES
  1,                         /* at early system startup, we run in  */
                             /*  kernel mode, so in trusted mode    */
#endif /* WITH_MEMORY_PROTECTION */
};

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2CONST(char, AUTOMATIC, OS_APPL_DATA) proc_name_table[TASK_COUNT + ISR_COUNT + 1] = {

  "write_audio",
  "inference",
  "copyDMAtoSRAM",
  "start_dma",
  "start_audio",
  "setup_inference",
  "start_sdcard",
  "isr_dma",
  "*idle*"
};
#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/* End of file tpl_app_config.c */
